# Generated by Django 3.2 on 2021-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ref_image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
